# Form implementation generated from reading ui file 'Vista.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1464, 977)
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.frame_superior = QtWidgets.QFrame(parent=self.centralwidget)
        self.frame_superior.setMinimumSize(QtCore.QSize(0, 50))
        self.frame_superior.setMaximumSize(QtCore.QSize(10000, 40))
        self.frame_superior.setStyleSheet("background-color: #6200EE;")
        self.frame_superior.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_superior.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_superior.setObjectName("frame_superior")
        self.pushButton_5 = QtWidgets.QPushButton(parent=self.frame_superior)
        self.pushButton_5.setGeometry(QtCore.QRect(50, 10, 101, 31))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("D:/PeoyectoPy/Veterinaria/Downloads/casa.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.pushButton_5.setIcon(icon)
        self.pushButton_5.setObjectName("pushButton_5")
        self.verticalLayout.addWidget(self.frame_superior)
        self.frame_inferior = QtWidgets.QFrame(parent=self.centralwidget)
        self.frame_inferior.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_inferior.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_inferior.setObjectName("frame_inferior")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.frame_inferior)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.frame_lateral = QtWidgets.QFrame(parent=self.frame_inferior)
        self.frame_lateral.setMinimumSize(QtCore.QSize(200, 0))
        self.frame_lateral.setMaximumSize(QtCore.QSize(600, 16777215))
        self.frame_lateral.setStyleSheet("background-color: rgb(211, 211, 211);")
        self.frame_lateral.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_lateral.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_lateral.setObjectName("frame_lateral")
        self.btnFormEditarProp = QtWidgets.QPushButton(parent=self.frame_lateral)
        self.btnFormEditarProp.setGeometry(QtCore.QRect(0, 100, 191, 41))
        self.btnFormEditarProp.setStyleSheet("QPushButton {\n"
"    background-color: white;\n"
"    color: black; \n"
"    border: 2px solid #6200EE; \n"
"    border-radius: 20px; \n"
"    padding: 10px; \n"
"    font-size: 14px; \n"
"    font-weight: bold; \n"
"    transition: background-color 0.3s; \n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #6200EE; \n"
"    color: white;\n"
"}")
        self.btnFormEditarProp.setObjectName("btnFormEditarProp")
        self.btnFormDeletProp = QtWidgets.QPushButton(parent=self.frame_lateral)
        self.btnFormDeletProp.setGeometry(QtCore.QRect(0, 140, 191, 51))
        self.btnFormDeletProp.setStyleSheet("QPushButton {\n"
"    background-color: white;\n"
"    color: black; \n"
"    border: 2px solid #6200EE; \n"
"    border-radius: 20px; \n"
"    padding: 10px; \n"
"    font-size: 14px; \n"
"    font-weight: bold; \n"
"    transition: background-color 0.3s; \n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #6200EE; \n"
"    color: white;\n"
"}")
        self.btnFormDeletProp.setObjectName("btnFormDeletProp")
        self.btnFormVerMascota = QtWidgets.QPushButton(parent=self.frame_lateral)
        self.btnFormVerMascota.setGeometry(QtCore.QRect(0, 190, 191, 51))
        self.btnFormVerMascota.setStyleSheet("QPushButton {\n"
"    background-color: white;\n"
"    color: black; \n"
"    border: 2px solid #6200EE; \n"
"    border-radius: 20px; \n"
"    padding: 10px; \n"
"    font-size: 14px; \n"
"    font-weight: bold; \n"
"    transition: background-color 0.3s; \n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #6200EE; \n"
"    color: white;\n"
"}")
        self.btnFormVerMascota.setObjectName("btnFormVerMascota")
        self.btnFormEditMascota = QtWidgets.QPushButton(parent=self.frame_lateral)
        self.btnFormEditMascota.setGeometry(QtCore.QRect(0, 250, 191, 41))
        self.btnFormEditMascota.setStyleSheet("QPushButton {\n"
"    background-color: white;\n"
"    color: black; \n"
"    border: 2px solid #6200EE; \n"
"    border-radius: 20px; \n"
"    padding: 10px; \n"
"    font-size: 14px; \n"
"    font-weight: bold; \n"
"    transition: background-color 0.3s; \n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #6200EE; \n"
"    color: white;\n"
"}")
        self.btnFormEditMascota.setObjectName("btnFormEditMascota")
        self.btnFormDeletMasco = QtWidgets.QPushButton(parent=self.frame_lateral)
        self.btnFormDeletMasco.setGeometry(QtCore.QRect(0, 290, 191, 51))
        self.btnFormDeletMasco.setStyleSheet("QPushButton {\n"
"    background-color: white;\n"
"    color: black; \n"
"    border: 2px solid #6200EE; \n"
"    border-radius: 20px; \n"
"    padding: 10px; \n"
"    font-size: 14px; \n"
"    font-weight: bold; \n"
"    transition: background-color 0.3s; \n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #6200EE; \n"
"    color: white;\n"
"}")
        self.btnFormDeletMasco.setObjectName("btnFormDeletMasco")
        self.btnFormVerEmp = QtWidgets.QPushButton(parent=self.frame_lateral)
        self.btnFormVerEmp.setGeometry(QtCore.QRect(0, 340, 191, 51))
        self.btnFormVerEmp.setStyleSheet("QPushButton {\n"
"    background-color: white;\n"
"    color: black; \n"
"    border: 2px solid #6200EE; \n"
"    border-radius: 20px; \n"
"    padding: 10px; \n"
"    font-size: 14px; \n"
"    font-weight: bold; \n"
"    transition: background-color 0.3s; \n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #6200EE; \n"
"    color: white;\n"
"}")
        self.btnFormVerEmp.setObjectName("btnFormVerEmp")
        self.btnFormEditEmp = QtWidgets.QPushButton(parent=self.frame_lateral)
        self.btnFormEditEmp.setGeometry(QtCore.QRect(0, 390, 201, 41))
        self.btnFormEditEmp.setStyleSheet("QPushButton {\n"
"    background-color: white;\n"
"    color: black; \n"
"    border: 2px solid #6200EE; \n"
"    border-radius: 20px; \n"
"    padding: 10px; \n"
"    font-size: 14px; \n"
"    font-weight: bold; \n"
"    transition: background-color 0.3s; \n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #6200EE; \n"
"    color: white;\n"
"}")
        self.btnFormEditEmp.setObjectName("btnFormEditEmp")
        self.btnFormDeletEmp = QtWidgets.QPushButton(parent=self.frame_lateral)
        self.btnFormDeletEmp.setGeometry(QtCore.QRect(0, 440, 201, 51))
        self.btnFormDeletEmp.setStyleSheet("QPushButton {\n"
"    background-color: white;\n"
"    color: black; \n"
"    border: 2px solid #6200EE; \n"
"    border-radius: 20px; \n"
"    padding: 10px; \n"
"    font-size: 14px; \n"
"    font-weight: bold; \n"
"    transition: background-color 0.3s; \n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #6200EE; \n"
"    color: white;\n"
"}")
        self.btnFormDeletEmp.setObjectName("btnFormDeletEmp")
        self.btnFormAtencion = QtWidgets.QPushButton(parent=self.frame_lateral)
        self.btnFormAtencion.setGeometry(QtCore.QRect(0, 500, 201, 51))
        self.btnFormAtencion.setStyleSheet("QPushButton {\n"
"    background-color: white;\n"
"    color: black; \n"
"    border: 2px solid #6200EE; \n"
"    border-radius: 20px; \n"
"    padding: 10px; \n"
"    font-size: 14px; \n"
"    font-weight: bold; \n"
"    transition: background-color 0.3s; \n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #6200EE; \n"
"    color: white;\n"
"}")
        self.btnFormAtencion.setObjectName("btnFormAtencion")
        self.btnVerPropietario = QtWidgets.QPushButton(parent=self.frame_lateral)
        self.btnVerPropietario.setGeometry(QtCore.QRect(0, 50, 201, 51))
        self.btnVerPropietario.setStyleSheet("QPushButton {\n"
"    background-color: white;\n"
"    color: black; \n"
"    border: 2px solid #6200EE; \n"
"    border-radius: 20px; \n"
"    padding: 10px; \n"
"    font-size: 14px; \n"
"    font-weight: bold; \n"
"    transition: background-color 0.3s; \n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #6200EE; \n"
"    color: white;\n"
"}\n"
"")
        self.btnVerPropietario.setObjectName("btnVerPropietario")
        self.btnFormInicio = QtWidgets.QPushButton(parent=self.frame_lateral)
        self.btnFormInicio.setGeometry(QtCore.QRect(0, 0, 191, 51))
        self.btnFormInicio.setStyleSheet("QPushButton {\n"
"    background-color: white; /* Color de fondo por defecto */\n"
"    color: black; /* Color del texto */\n"
"    border: 2px solid #6200EE; /* Borde violeta */\n"
"    border-radius: 20px; /* Botón redondo */\n"
"    padding: 10px; /* Espaciado interno */\n"
"    font-size: 14px; /* Tamaño de la fuente */\n"
"    font-weight: bold; /* Fuente en negrita */\n"
"    transition: background-color 0.3s; /* Transición suave para el cambio de color */\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #6200EE; /* Color violeta cuando se pasa el cursor */\n"
"    color: white; /* Cambia el texto a blanco */\n"
"}\n"
"")
        self.btnFormInicio.setObjectName("btnFormInicio")
        self.btnFormAgregarAtencion = QtWidgets.QPushButton(parent=self.frame_lateral)
        self.btnFormAgregarAtencion.setGeometry(QtCore.QRect(0, 560, 191, 51))
        self.btnFormAgregarAtencion.setStyleSheet("QPushButton {\n"
"    background-color: white;\n"
"    color: black; \n"
"    border: 2px solid #6200EE; \n"
"    border-radius: 20px; \n"
"    padding: 10px; \n"
"    font-size: 14px; \n"
"    font-weight: bold; \n"
"    transition: background-color 0.3s; \n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #6200EE; \n"
"    color: white;\n"
"}")
        self.btnFormAgregarAtencion.setObjectName("btnFormAgregarAtencion")
        self.btnFormEditAtencion = QtWidgets.QPushButton(parent=self.frame_lateral)
        self.btnFormEditAtencion.setGeometry(QtCore.QRect(0, 610, 191, 51))
        self.btnFormEditAtencion.setStyleSheet("QPushButton {\n"
"    background-color: white;\n"
"    color: black; \n"
"    border: 2px solid #6200EE; \n"
"    border-radius: 20px; \n"
"    padding: 10px; \n"
"    font-size: 14px; \n"
"    font-weight: bold; \n"
"    transition: background-color 0.3s; \n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #6200EE; \n"
"    color: white;\n"
"}")
        self.btnFormEditAtencion.setObjectName("btnFormEditAtencion")
        self.btnFormVerPractica = QtWidgets.QPushButton(parent=self.frame_lateral)
        self.btnFormVerPractica.setGeometry(QtCore.QRect(0, 660, 191, 51))
        self.btnFormVerPractica.setStyleSheet("QPushButton {\n"
"    background-color: white;\n"
"    color: black; \n"
"    border: 2px solid #6200EE; \n"
"    border-radius: 20px; \n"
"    padding: 10px; \n"
"    font-size: 14px; \n"
"    font-weight: bold; \n"
"    transition: background-color 0.3s; \n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #6200EE; \n"
"    color: white;\n"
"}")
        self.btnFormVerPractica.setObjectName("btnFormVerPractica")
        self.btnFormAgregarPractica = QtWidgets.QPushButton(parent=self.frame_lateral)
        self.btnFormAgregarPractica.setGeometry(QtCore.QRect(0, 720, 191, 41))
        self.btnFormAgregarPractica.setStyleSheet("QPushButton {\n"
"    background-color: white;\n"
"    color: black; \n"
"    border: 2px solid #6200EE; \n"
"    border-radius: 20px; \n"
"    padding: 10px; \n"
"    font-size: 14px; \n"
"    font-weight: bold; \n"
"    transition: background-color 0.3s; \n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #6200EE; \n"
"    color: white;\n"
"}")
        self.btnFormAgregarPractica.setObjectName("btnFormAgregarPractica")
        self.btnFormAgregarEmp = QtWidgets.QPushButton(parent=self.frame_lateral)
        self.btnFormAgregarEmp.setGeometry(QtCore.QRect(0, 760, 191, 41))
        self.btnFormAgregarEmp.setStyleSheet("QPushButton {\n"
"    background-color: white; /* Color de fondo por defecto */\n"
"    color: black; /* Color del texto */\n"
"    border: 2px solid #6200EE; /* Borde violeta */\n"
"    border-radius: 20px; /* Botón redondo */\n"
"    padding: 10px; /* Espaciado interno */\n"
"    font-size: 14px; /* Tamaño de la fuente */\n"
"    font-weight: bold; /* Fuente en negrita */\n"
"    transition: background-color 0.3s; /* Transición suave para el cambio de color */\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #6200EE; /* Color violeta cuando se pasa el cursor */\n"
"    color: white; /* Cambia el texto a blanco */\n"
"}\n"
"")
        self.btnFormAgregarEmp.setObjectName("btnFormAgregarEmp")
        self.btnFormAgregarProp = QtWidgets.QPushButton(parent=self.frame_lateral)
        self.btnFormAgregarProp.setGeometry(QtCore.QRect(0, 800, 191, 41))
        self.btnFormAgregarProp.setStyleSheet("QPushButton {\n"
"    background-color: white; /* Color de fondo por defecto */\n"
"    color: black; /* Color del texto */\n"
"    border: 2px solid #6200EE; /* Borde violeta */\n"
"    border-radius: 20px; /* Botón redondo */\n"
"    padding: 10px; /* Espaciado interno */\n"
"    font-size: 14px; /* Tamaño de la fuente */\n"
"    font-weight: bold; /* Fuente en negrita */\n"
"    transition: background-color 0.3s; /* Transición suave para el cambio de color */\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #6200EE; /* Color violeta cuando se pasa el cursor */\n"
"    color: white; /* Cambia el texto a blanco */\n"
"}\n"
"")
        self.btnFormAgregarProp.setObjectName("btnFormAgregarProp")
        self.btnFormAgregarMascota = QtWidgets.QPushButton(parent=self.frame_lateral)
        self.btnFormAgregarMascota.setGeometry(QtCore.QRect(0, 840, 191, 41))
        self.btnFormAgregarMascota.setStyleSheet("QPushButton {\n"
"    background-color: white; /* Color de fondo por defecto */\n"
"    color: black; /* Color del texto */\n"
"    border: 2px solid #6200EE; /* Borde violeta */\n"
"    border-radius: 20px; /* Botón redondo */\n"
"    padding: 10px; /* Espaciado interno */\n"
"    font-size: 14px; /* Tamaño de la fuente */\n"
"    font-weight: bold; /* Fuente en negrita */\n"
"    transition: background-color 0.3s; /* Transición suave para el cambio de color */\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #6200EE; /* Color violeta cuando se pasa el cursor */\n"
"    color: white; /* Cambia el texto a blanco */\n"
"}\n"
"")
        self.btnFormAgregarMascota.setObjectName("btnFormAgregarMascota")
        self.horizontalLayout.addWidget(self.frame_lateral)
        self.frame_2 = QtWidgets.QFrame(parent=self.frame_inferior)
        self.frame_2.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_2.setObjectName("frame_2")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.frame_2)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.stackedWidget = QtWidgets.QStackedWidget(parent=self.frame_2)
        self.stackedWidget.setObjectName("stackedWidget")
        self.page_inicio = QtWidgets.QWidget()
        self.page_inicio.setObjectName("page_inicio")
        self.stackedWidget.addWidget(self.page_inicio)
        self.page_editarAtencion = QtWidgets.QWidget()
        self.page_editarAtencion.setObjectName("page_editarAtencion")
        self.btnEditarMascota_6 = QtWidgets.QPushButton(parent=self.page_editarAtencion)
        self.btnEditarMascota_6.setGeometry(QtCore.QRect(380, 470, 151, 71))
        self.btnEditarMascota_6.setObjectName("btnEditarMascota_6")
        self.txtDniMascotaEdit_2 = QtWidgets.QLineEdit(parent=self.page_editarAtencion)
        self.txtDniMascotaEdit_2.setGeometry(QtCore.QRect(350, 290, 221, 51))
        self.txtDniMascotaEdit_2.setStyleSheet("QLineEdit {\n"
"    background-color: #f4f4f4; /* Fondo claro */\n"
"    color: #333; /* Texto oscuro */\n"
"    border: 2px solid #ccc; /* Borde inicial */\n"
"    border-radius: 10px; /* Bordes redondeados */\n"
"    padding: 8px; /* Espaciado interno */\n"
"    font-size: 14px; /* Tamaño de texto */\n"
"    font-family: \"Arial\", sans-serif; /* Fuente limpia y moderna */\n"
"}\n"
"\n"
"QLineEdit:focus {\n"
"    border: 2px solid #6200ee; /* Cambia el color del borde al enfocarse */\n"
"    background-color: #ffffff; /* Fondo blanco al enfocarse */\n"
"    color: #000; /* Texto más oscuro */\n"
"}")
        self.txtDniMascotaEdit_2.setText("")
        self.txtDniMascotaEdit_2.setObjectName("txtDniMascotaEdit_2")
        self.txtObservacion_2 = QtWidgets.QTextEdit(parent=self.page_editarAtencion)
        self.txtObservacion_2.setGeometry(QtCore.QRect(350, 360, 221, 71))
        self.txtObservacion_2.setObjectName("txtObservacion_2")
        self.txtCodMascotaEdit_7 = QtWidgets.QLineEdit(parent=self.page_editarAtencion)
        self.txtCodMascotaEdit_7.setGeometry(QtCore.QRect(350, 230, 221, 51))
        self.txtCodMascotaEdit_7.setStyleSheet("QLineEdit {\n"
"    background-color: #f4f4f4; /* Fondo claro */\n"
"    color: #333; /* Texto oscuro */\n"
"    border: 2px solid #ccc; /* Borde inicial */\n"
"    border-radius: 10px; /* Bordes redondeados */\n"
"    padding: 8px; /* Espaciado interno */\n"
"    font-size: 14px; /* Tamaño de texto */\n"
"    font-family: \"Arial\", sans-serif; /* Fuente limpia y moderna */\n"
"}\n"
"\n"
"QLineEdit:focus {\n"
"    border: 2px solid #6200ee; /* Cambia el color del borde al enfocarse */\n"
"    background-color: #ffffff; /* Fondo blanco al enfocarse */\n"
"    color: #000; /* Texto más oscuro */\n"
"}")
        self.txtCodMascotaEdit_7.setText("")
        self.txtCodMascotaEdit_7.setObjectName("txtCodMascotaEdit_7")
        self.label_13 = QtWidgets.QLabel(parent=self.page_editarAtencion)
        self.label_13.setGeometry(QtCore.QRect(290, 150, 451, 51))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        self.label_13.setFont(font)
        self.label_13.setTextFormat(QtCore.Qt.TextFormat.AutoText)
        self.label_13.setWordWrap(False)
        self.label_13.setObjectName("label_13")
        self.stackedWidget.addWidget(self.page_editarAtencion)
        self.page_VerEmpleado = QtWidgets.QWidget()
        self.page_VerEmpleado.setObjectName("page_VerEmpleado")
        self.tableWidget = QtWidgets.QTableWidget(parent=self.page_VerEmpleado)
        self.tableWidget.setGeometry(QtCore.QRect(90, 270, 691, 281))
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(6)
        self.tableWidget.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(5, item)
        self.pushButton_17 = QtWidgets.QPushButton(parent=self.page_VerEmpleado)
        self.pushButton_17.setGeometry(QtCore.QRect(300, 60, 151, 24))
        self.pushButton_17.setObjectName("pushButton_17")
        self.txtNombreFiltroEmp = QtWidgets.QLineEdit(parent=self.page_VerEmpleado)
        self.txtNombreFiltroEmp.setGeometry(QtCore.QRect(100, 50, 191, 41))
        self.txtNombreFiltroEmp.setStyleSheet("QLineEdit {\n"
"    background-color: #f4f4f4; /* Fondo claro */\n"
"    color: #333; /* Texto oscuro */\n"
"    border: 2px solid #ccc; /* Borde inicial */\n"
"    border-radius: 10px; /* Bordes redondeados */\n"
"    padding: 8px; /* Espaciado interno */\n"
"    font-size: 14px; /* Tamaño de texto */\n"
"    font-family: \"Arial\", sans-serif; /* Fuente limpia y moderna */\n"
"}\n"
"\n"
"QLineEdit:focus {\n"
"    border: 2px solid #6200ee; /* Cambia el color del borde al enfocarse */\n"
"    background-color: #ffffff; /* Fondo blanco al enfocarse */\n"
"    color: #000; /* Texto más oscuro */\n"
"}")
        self.txtNombreFiltroEmp.setObjectName("txtNombreFiltroEmp")
        self.stackedWidget.addWidget(self.page_VerEmpleado)
        self.page_EliminarMascota = QtWidgets.QWidget()
        self.page_EliminarMascota.setObjectName("page_EliminarMascota")
        self.label_10 = QtWidgets.QLabel(parent=self.page_EliminarMascota)
        self.label_10.setGeometry(QtCore.QRect(250, 130, 151, 51))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        self.label_10.setFont(font)
        self.label_10.setTextFormat(QtCore.Qt.TextFormat.AutoText)
        self.label_10.setWordWrap(False)
        self.label_10.setObjectName("label_10")
        self.btnEliminarMascota = QtWidgets.QPushButton(parent=self.page_EliminarMascota)
        self.btnEliminarMascota.setGeometry(QtCore.QRect(250, 270, 151, 71))
        self.btnEliminarMascota.setObjectName("btnEliminarMascota")
        self.txtCodMascotaEliminar = QtWidgets.QLineEdit(parent=self.page_EliminarMascota)
        self.txtCodMascotaEliminar.setGeometry(QtCore.QRect(220, 200, 221, 51))
        self.txtCodMascotaEliminar.setStyleSheet("QLineEdit {\n"
"    background-color: #f4f4f4; /* Fondo claro */\n"
"    color: #333; /* Texto oscuro */\n"
"    border: 2px solid #ccc; /* Borde inicial */\n"
"    border-radius: 10px; /* Bordes redondeados */\n"
"    padding: 8px; /* Espaciado interno */\n"
"    font-size: 14px; /* Tamaño de texto */\n"
"    font-family: \"Arial\", sans-serif; /* Fuente limpia y moderna */\n"
"}\n"
"\n"
"QLineEdit:focus {\n"
"    border: 2px solid #6200ee; /* Cambia el color del borde al enfocarse */\n"
"    background-color: #ffffff; /* Fondo blanco al enfocarse */\n"
"    color: #000; /* Texto más oscuro */\n"
"}")
        self.txtCodMascotaEliminar.setObjectName("txtCodMascotaEliminar")
        self.stackedWidget.addWidget(self.page_EliminarMascota)
        self.page_EditarMascota = QtWidgets.QWidget()
        self.page_EditarMascota.setObjectName("page_EditarMascota")
        self.txtCodMascotaEdit = QtWidgets.QLineEdit(parent=self.page_EditarMascota)
        self.txtCodMascotaEdit.setGeometry(QtCore.QRect(260, 120, 221, 51))
        self.txtCodMascotaEdit.setStyleSheet("QLineEdit {\n"
"    background-color: #f4f4f4; /* Fondo claro */\n"
"    color: #333; /* Texto oscuro */\n"
"    border: 2px solid #ccc; /* Borde inicial */\n"
"    border-radius: 10px; /* Bordes redondeados */\n"
"    padding: 8px; /* Espaciado interno */\n"
"    font-size: 14px; /* Tamaño de texto */\n"
"    font-family: \"Arial\", sans-serif; /* Fuente limpia y moderna */\n"
"}\n"
"\n"
"QLineEdit:focus {\n"
"    border: 2px solid #6200ee; /* Cambia el color del borde al enfocarse */\n"
"    background-color: #ffffff; /* Fondo blanco al enfocarse */\n"
"    color: #000; /* Texto más oscuro */\n"
"}")
        self.txtCodMascotaEdit.setObjectName("txtCodMascotaEdit")
        self.txtDniMascotaEdit = QtWidgets.QLineEdit(parent=self.page_EditarMascota)
        self.txtDniMascotaEdit.setGeometry(QtCore.QRect(260, 180, 221, 51))
        self.txtDniMascotaEdit.setStyleSheet("QLineEdit {\n"
"    background-color: #f4f4f4; /* Fondo claro */\n"
"    color: #333; /* Texto oscuro */\n"
"    border: 2px solid #ccc; /* Borde inicial */\n"
"    border-radius: 10px; /* Bordes redondeados */\n"
"    padding: 8px; /* Espaciado interno */\n"
"    font-size: 14px; /* Tamaño de texto */\n"
"    font-family: \"Arial\", sans-serif; /* Fuente limpia y moderna */\n"
"}\n"
"\n"
"QLineEdit:focus {\n"
"    border: 2px solid #6200ee; /* Cambia el color del borde al enfocarse */\n"
"    background-color: #ffffff; /* Fondo blanco al enfocarse */\n"
"    color: #000; /* Texto más oscuro */\n"
"}")
        self.txtDniMascotaEdit.setObjectName("txtDniMascotaEdit")
        self.txtPeso = QtWidgets.QLineEdit(parent=self.page_EditarMascota)
        self.txtPeso.setGeometry(QtCore.QRect(260, 250, 221, 51))
        self.txtPeso.setStyleSheet("QLineEdit {\n"
"    background-color: #f4f4f4; /* Fondo claro */\n"
"    color: #333; /* Texto oscuro */\n"
"    border: 2px solid #ccc; /* Borde inicial */\n"
"    border-radius: 10px; /* Bordes redondeados */\n"
"    padding: 8px; /* Espaciado interno */\n"
"    font-size: 14px; /* Tamaño de texto */\n"
"    font-family: \"Arial\", sans-serif; /* Fuente limpia y moderna */\n"
"}\n"
"\n"
"QLineEdit:focus {\n"
"    border: 2px solid #6200ee; /* Cambia el color del borde al enfocarse */\n"
"    background-color: #ffffff; /* Fondo blanco al enfocarse */\n"
"    color: #000; /* Texto más oscuro */\n"
"}")
        self.txtPeso.setObjectName("txtPeso")
        self.txtObservacion = QtWidgets.QTextEdit(parent=self.page_EditarMascota)
        self.txtObservacion.setGeometry(QtCore.QRect(260, 310, 221, 71))
        self.txtObservacion.setObjectName("txtObservacion")
        self.txtFechaNacimiento = QtWidgets.QDateEdit(parent=self.page_EditarMascota)
        self.txtFechaNacimiento.setGeometry(QtCore.QRect(260, 470, 221, 61))
        self.txtFechaNacimiento.setObjectName("txtFechaNacimiento")
        self.label_5 = QtWidgets.QLabel(parent=self.page_EditarMascota)
        self.label_5.setGeometry(QtCore.QRect(100, 470, 141, 61))
        self.label_5.setTextFormat(QtCore.Qt.TextFormat.AutoText)
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(parent=self.page_EditarMascota)
        self.label_6.setGeometry(QtCore.QRect(200, 40, 451, 51))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        self.label_6.setFont(font)
        self.label_6.setTextFormat(QtCore.Qt.TextFormat.AutoText)
        self.label_6.setWordWrap(False)
        self.label_6.setObjectName("label_6")
        self.btnEditarMascota = QtWidgets.QPushButton(parent=self.page_EditarMascota)
        self.btnEditarMascota.setGeometry(QtCore.QRect(280, 550, 151, 71))
        self.btnEditarMascota.setObjectName("btnEditarMascota")
        self.txtNombreMasco = QtWidgets.QLineEdit(parent=self.page_EditarMascota)
        self.txtNombreMasco.setGeometry(QtCore.QRect(260, 400, 221, 51))
        self.txtNombreMasco.setStyleSheet("QLineEdit {\n"
"    background-color: #f4f4f4; /* Fondo claro */\n"
"    color: #333; /* Texto oscuro */\n"
"    border: 2px solid #ccc; /* Borde inicial */\n"
"    border-radius: 10px; /* Bordes redondeados */\n"
"    padding: 8px; /* Espaciado interno */\n"
"    font-size: 14px; /* Tamaño de texto */\n"
"    font-family: \"Arial\", sans-serif; /* Fuente limpia y moderna */\n"
"}\n"
"\n"
"QLineEdit:focus {\n"
"    border: 2px solid #6200ee; /* Cambia el color del borde al enfocarse */\n"
"    background-color: #ffffff; /* Fondo blanco al enfocarse */\n"
"    color: #000; /* Texto más oscuro */\n"
"}")
        self.txtNombreMasco.setObjectName("txtNombreMasco")
        self.stackedWidget.addWidget(self.page_EditarMascota)
        self.page_VerMascotas = QtWidgets.QWidget()
        self.page_VerMascotas.setObjectName("page_VerMascotas")
        self.txtNombreFiltroEmp_3 = QtWidgets.QLineEdit(parent=self.page_VerMascotas)
        self.txtNombreFiltroEmp_3.setGeometry(QtCore.QRect(260, 170, 191, 41))
        self.txtNombreFiltroEmp_3.setStyleSheet("QLineEdit {\n"
"    background-color: #f4f4f4; /* Fondo claro */\n"
"    color: #333; /* Texto oscuro */\n"
"    border: 2px solid #ccc; /* Borde inicial */\n"
"    border-radius: 10px; /* Bordes redondeados */\n"
"    padding: 8px; /* Espaciado interno */\n"
"    font-size: 14px; /* Tamaño de texto */\n"
"    font-family: \"Arial\", sans-serif; /* Fuente limpia y moderna */\n"
"}\n"
"\n"
"QLineEdit:focus {\n"
"    border: 2px solid #6200ee; /* Cambia el color del borde al enfocarse */\n"
"    background-color: #ffffff; /* Fondo blanco al enfocarse */\n"
"    color: #000; /* Texto más oscuro */\n"
"}")
        self.txtNombreFiltroEmp_3.setObjectName("txtNombreFiltroEmp_3")
        self.pushButton_19 = QtWidgets.QPushButton(parent=self.page_VerMascotas)
        self.pushButton_19.setGeometry(QtCore.QRect(460, 180, 171, 24))
        self.pushButton_19.setObjectName("pushButton_19")
        self.grdMascotas = QtWidgets.QTableWidget(parent=self.page_VerMascotas)
        self.grdMascotas.setGeometry(QtCore.QRect(170, 280, 691, 281))
        self.grdMascotas.setObjectName("grdMascotas")
        self.grdMascotas.setColumnCount(7)
        self.grdMascotas.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.grdMascotas.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.grdMascotas.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.grdMascotas.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.grdMascotas.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.grdMascotas.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.grdMascotas.setHorizontalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.grdMascotas.setHorizontalHeaderItem(6, item)
        self.txtNombreFiltroEmp_6 = QtWidgets.QLineEdit(parent=self.page_VerMascotas)
        self.txtNombreFiltroEmp_6.setGeometry(QtCore.QRect(260, 220, 191, 41))
        self.txtNombreFiltroEmp_6.setStyleSheet("QLineEdit {\n"
"    background-color: #f4f4f4; /* Fondo claro */\n"
"    color: #333; /* Texto oscuro */\n"
"    border: 2px solid #ccc; /* Borde inicial */\n"
"    border-radius: 10px; /* Bordes redondeados */\n"
"    padding: 8px; /* Espaciado interno */\n"
"    font-size: 14px; /* Tamaño de texto */\n"
"    font-family: \"Arial\", sans-serif; /* Fuente limpia y moderna */\n"
"}\n"
"\n"
"QLineEdit:focus {\n"
"    border: 2px solid #6200ee; /* Cambia el color del borde al enfocarse */\n"
"    background-color: #ffffff; /* Fondo blanco al enfocarse */\n"
"    color: #000; /* Texto más oscuro */\n"
"}")
        self.txtNombreFiltroEmp_6.setObjectName("txtNombreFiltroEmp_6")
        self.pushButton_22 = QtWidgets.QPushButton(parent=self.page_VerMascotas)
        self.pushButton_22.setGeometry(QtCore.QRect(460, 230, 171, 24))
        self.pushButton_22.setObjectName("pushButton_22")
        self.stackedWidget.addWidget(self.page_VerMascotas)
        self.page_EliminarPropietario = QtWidgets.QWidget()
        self.page_EliminarPropietario.setObjectName("page_EliminarPropietario")
        self.label_11 = QtWidgets.QLabel(parent=self.page_EliminarPropietario)
        self.label_11.setGeometry(QtCore.QRect(260, 140, 211, 51))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        self.label_11.setFont(font)
        self.label_11.setTextFormat(QtCore.Qt.TextFormat.AutoText)
        self.label_11.setWordWrap(False)
        self.label_11.setObjectName("label_11")
        self.btnEmpEliminar = QtWidgets.QPushButton(parent=self.page_EliminarPropietario)
        self.btnEmpEliminar.setGeometry(QtCore.QRect(270, 280, 141, 51))
        self.btnEmpEliminar.setObjectName("btnEmpEliminar")
        self.txtDniEliminar = QtWidgets.QLineEdit(parent=self.page_EliminarPropietario)
        self.txtDniEliminar.setGeometry(QtCore.QRect(230, 210, 221, 51))
        self.txtDniEliminar.setStyleSheet("QLineEdit {\n"
"    background-color: #f4f4f4; /* Fondo claro */\n"
"    color: #333; /* Texto oscuro */\n"
"    border: 2px solid #ccc; /* Borde inicial */\n"
"    border-radius: 10px; /* Bordes redondeados */\n"
"    padding: 8px; /* Espaciado interno */\n"
"    font-size: 14px; /* Tamaño de texto */\n"
"    font-family: \"Arial\", sans-serif; /* Fuente limpia y moderna */\n"
"}\n"
"\n"
"QLineEdit:focus {\n"
"    border: 2px solid #6200ee; /* Cambia el color del borde al enfocarse */\n"
"    background-color: #ffffff; /* Fondo blanco al enfocarse */\n"
"    color: #000; /* Texto más oscuro */\n"
"}")
        self.txtDniEliminar.setObjectName("txtDniEliminar")
        self.stackedWidget.addWidget(self.page_EliminarPropietario)
        self.page_AgregarPropietario = QtWidgets.QWidget()
        self.page_AgregarPropietario.setObjectName("page_AgregarPropietario")
        self.label_3 = QtWidgets.QLabel(parent=self.page_AgregarPropietario)
        self.label_3.setGeometry(QtCore.QRect(160, 60, 451, 51))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        self.label_3.setFont(font)
        self.label_3.setTextFormat(QtCore.Qt.TextFormat.AutoText)
        self.label_3.setWordWrap(False)
        self.label_3.setObjectName("label_3")
        self.txtDni = QtWidgets.QLineEdit(parent=self.page_AgregarPropietario)
        self.txtDni.setGeometry(QtCore.QRect(600, 280, 221, 61))
        self.txtDni.setStyleSheet("QLineEdit {\n"
"    background-color: #f4f4f4; /* Fondo claro */\n"
"    color: #333; /* Texto oscuro */\n"
"    border: 2px solid #ccc; /* Borde inicial */\n"
"    border-radius: 10px; /* Bordes redondeados */\n"
"    padding: 8px; /* Espaciado interno */\n"
"    font-size: 14px; /* Tamaño de texto */\n"
"    font-family: \"Arial\", sans-serif; /* Fuente limpia y moderna */\n"
"}\n"
"\n"
"QLineEdit:focus {\n"
"    border: 2px solid #6200ee; /* Cambia el color del borde al enfocarse */\n"
"    background-color: #ffffff; /* Fondo blanco al enfocarse */\n"
"    color: #000; /* Texto más oscuro */\n"
"}")
        self.txtDni.setObjectName("txtDni")
        self.txtNombre = QtWidgets.QLineEdit(parent=self.page_AgregarPropietario)
        self.txtNombre.setGeometry(QtCore.QRect(600, 210, 221, 61))
        self.txtNombre.setStyleSheet("QLineEdit {\n"
"    background-color: #f4f4f4; /* Fondo claro */\n"
"    color: #333; /* Texto oscuro */\n"
"    border: 2px solid #ccc; /* Borde inicial */\n"
"    border-radius: 10px; /* Bordes redondeados */\n"
"    padding: 8px; /* Espaciado interno */\n"
"    font-size: 14px; /* Tamaño de texto */\n"
"    font-family: \"Arial\", sans-serif; /* Fuente limpia y moderna */\n"
"}\n"
"\n"
"QLineEdit:focus {\n"
"    border: 2px solid #6200ee; /* Cambia el color del borde al enfocarse */\n"
"    background-color: #ffffff; /* Fondo blanco al enfocarse */\n"
"    color: #000; /* Texto más oscuro */\n"
"}")
        self.txtNombre.setObjectName("txtNombre")
        self.txtApellido = QtWidgets.QLineEdit(parent=self.page_AgregarPropietario)
        self.txtApellido.setGeometry(QtCore.QRect(370, 210, 211, 61))
        self.txtApellido.setStyleSheet("QLineEdit {\n"
"    background-color: #f4f4f4; /* Fondo claro */\n"
"    color: #333; /* Texto oscuro */\n"
"    border: 2px solid #ccc; /* Borde inicial */\n"
"    border-radius: 10px; /* Bordes redondeados */\n"
"    padding: 8px; /* Espaciado interno */\n"
"    font-size: 14px; /* Tamaño de texto */\n"
"    font-family: \"Arial\", sans-serif; /* Fuente limpia y moderna */\n"
"}\n"
"\n"
"QLineEdit:focus {\n"
"    border: 2px solid #6200ee; /* Cambia el color del borde al enfocarse */\n"
"    background-color: #ffffff; /* Fondo blanco al enfocarse */\n"
"    color: #000; /* Texto más oscuro */\n"
"}")
        self.txtApellido.setObjectName("txtApellido")
        self.txtCorreo = QtWidgets.QLineEdit(parent=self.page_AgregarPropietario)
        self.txtCorreo.setGeometry(QtCore.QRect(370, 350, 211, 61))
        self.txtCorreo.setStyleSheet("QLineEdit {\n"
"    background-color: #f4f4f4; /* Fondo claro */\n"
"    color: #333; /* Texto oscuro */\n"
"    border: 2px solid #ccc; /* Borde inicial */\n"
"    border-radius: 10px; /* Bordes redondeados */\n"
"    padding: 8px; /* Espaciado interno */\n"
"    font-size: 14px; /* Tamaño de texto */\n"
"    font-family: \"Arial\", sans-serif; /* Fuente limpia y moderna */\n"
"}\n"
"\n"
"QLineEdit:focus {\n"
"    border: 2px solid #6200ee; /* Cambia el color del borde al enfocarse */\n"
"    background-color: #ffffff; /* Fondo blanco al enfocarse */\n"
"    color: #000; /* Texto más oscuro */\n"
"}")
        self.txtCorreo.setObjectName("txtCorreo")
        self.txtTelefono = QtWidgets.QLineEdit(parent=self.page_AgregarPropietario)
        self.txtTelefono.setGeometry(QtCore.QRect(370, 280, 211, 61))
        self.txtTelefono.setStyleSheet("QLineEdit {\n"
"    background-color: #f4f4f4; /* Fondo claro */\n"
"    color: #333; /* Texto oscuro */\n"
"    border: 2px solid #ccc; /* Borde inicial */\n"
"    border-radius: 10px; /* Bordes redondeados */\n"
"    padding: 8px; /* Espaciado interno */\n"
"    font-size: 14px; /* Tamaño de texto */\n"
"    font-family: \"Arial\", sans-serif; /* Fuente limpia y moderna */\n"
"}\n"
"\n"
"QLineEdit:focus {\n"
"    border: 2px solid #6200ee; /* Cambia el color del borde al enfocarse */\n"
"    background-color: #ffffff; /* Fondo blanco al enfocarse */\n"
"    color: #000; /* Texto más oscuro */\n"
"}")
        self.txtTelefono.setObjectName("txtTelefono")
        self.btnInsertarPropietario = QtWidgets.QPushButton(parent=self.page_AgregarPropietario)
        self.btnInsertarPropietario.setGeometry(QtCore.QRect(510, 430, 161, 41))
        self.btnInsertarPropietario.setObjectName("btnInsertarPropietario")
        self.txtCorreo_2 = QtWidgets.QLineEdit(parent=self.page_AgregarPropietario)
        self.txtCorreo_2.setGeometry(QtCore.QRect(600, 350, 221, 61))
        self.txtCorreo_2.setStyleSheet("QLineEdit {\n"
"    background-color: #f4f4f4; /* Fondo claro */\n"
"    color: #333; /* Texto oscuro */\n"
"    border: 2px solid #ccc; /* Borde inicial */\n"
"    border-radius: 10px; /* Bordes redondeados */\n"
"    padding: 8px; /* Espaciado interno */\n"
"    font-size: 14px; /* Tamaño de texto */\n"
"    font-family: \"Arial\", sans-serif; /* Fuente limpia y moderna */\n"
"}\n"
"\n"
"QLineEdit:focus {\n"
"    border: 2px solid #6200ee; /* Cambia el color del borde al enfocarse */\n"
"    background-color: #ffffff; /* Fondo blanco al enfocarse */\n"
"    color: #000; /* Texto más oscuro */\n"
"}")
        self.txtCorreo_2.setObjectName("txtCorreo_2")
        self.stackedWidget.addWidget(self.page_AgregarPropietario)
        self.page_VerPropietario = QtWidgets.QWidget()
        self.page_VerPropietario.setObjectName("page_VerPropietario")
        self.txtBuscarDni = QtWidgets.QLineEdit(parent=self.page_VerPropietario)
        self.txtBuscarDni.setGeometry(QtCore.QRect(380, 250, 191, 41))
        self.txtBuscarDni.setStyleSheet("QLineEdit {\n"
"    background-color: #f4f4f4; /* Fondo claro */\n"
"    color: #333; /* Texto oscuro */\n"
"    border: 2px solid #ccc; /* Borde inicial */\n"
"    border-radius: 10px; /* Bordes redondeados */\n"
"    padding: 8px; /* Espaciado interno */\n"
"    font-size: 14px; /* Tamaño de texto */\n"
"    font-family: \"Arial\", sans-serif; /* Fuente limpia y moderna */\n"
"}\n"
"\n"
"QLineEdit:focus {\n"
"    border: 2px solid #6200ee; /* Cambia el color del borde al enfocarse */\n"
"    background-color: #ffffff; /* Fondo blanco al enfocarse */\n"
"    color: #000; /* Texto más oscuro */\n"
"}")
        self.txtBuscarDni.setObjectName("txtBuscarDni")
        self.btnbuscaDni = QtWidgets.QPushButton(parent=self.page_VerPropietario)
        self.btnbuscaDni.setGeometry(QtCore.QRect(580, 260, 151, 24))
        self.btnbuscaDni.setObjectName("btnbuscaDni")
        self.grdPropietario = QtWidgets.QTableWidget(parent=self.page_VerPropietario)
        self.grdPropietario.setGeometry(QtCore.QRect(120, 380, 691, 281))
        self.grdPropietario.setObjectName("grdPropietario")
        self.grdPropietario.setColumnCount(6)
        self.grdPropietario.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.grdPropietario.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.grdPropietario.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.grdPropietario.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.grdPropietario.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.grdPropietario.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.grdPropietario.setHorizontalHeaderItem(5, item)
        self.stackedWidget.addWidget(self.page_VerPropietario)
        self.page_EditarPropietario = QtWidgets.QWidget()
        self.page_EditarPropietario.setObjectName("page_EditarPropietario")
        self.txtNombreEdit = QtWidgets.QLineEdit(parent=self.page_EditarPropietario)
        self.txtNombreEdit.setGeometry(QtCore.QRect(270, 170, 221, 51))
        self.txtNombreEdit.setStyleSheet("QLineEdit {\n"
"    background-color: #f4f4f4; /* Fondo claro */\n"
"    color: #333; /* Texto oscuro */\n"
"    border: 2px solid #ccc; /* Borde inicial */\n"
"    border-radius: 10px; /* Bordes redondeados */\n"
"    padding: 8px; /* Espaciado interno */\n"
"    font-size: 14px; /* Tamaño de texto */\n"
"    font-family: \"Arial\", sans-serif; /* Fuente limpia y moderna */\n"
"}\n"
"\n"
"QLineEdit:focus {\n"
"    border: 2px solid #6200ee; /* Cambia el color del borde al enfocarse */\n"
"    background-color: #ffffff; /* Fondo blanco al enfocarse */\n"
"    color: #000; /* Texto más oscuro */\n"
"}")
        self.txtNombreEdit.setObjectName("txtNombreEdit")
        self.txtApellidoEdit = QtWidgets.QLineEdit(parent=self.page_EditarPropietario)
        self.txtApellidoEdit.setGeometry(QtCore.QRect(270, 230, 221, 51))
        self.txtApellidoEdit.setStyleSheet("QLineEdit {\n"
"    background-color: #f4f4f4; /* Fondo claro */\n"
"    color: #333; /* Texto oscuro */\n"
"    border: 2px solid #ccc; /* Borde inicial */\n"
"    border-radius: 10px; /* Bordes redondeados */\n"
"    padding: 8px; /* Espaciado interno */\n"
"    font-size: 14px; /* Tamaño de texto */\n"
"    font-family: \"Arial\", sans-serif; /* Fuente limpia y moderna */\n"
"}\n"
"\n"
"QLineEdit:focus {\n"
"    border: 2px solid #6200ee; /* Cambia el color del borde al enfocarse */\n"
"    background-color: #ffffff; /* Fondo blanco al enfocarse */\n"
"    color: #000; /* Texto más oscuro */\n"
"}")
        self.txtApellidoEdit.setObjectName("txtApellidoEdit")
        self.txtDireccionEdit = QtWidgets.QLineEdit(parent=self.page_EditarPropietario)
        self.txtDireccionEdit.setGeometry(QtCore.QRect(270, 290, 221, 51))
        self.txtDireccionEdit.setStyleSheet("QLineEdit {\n"
"    background-color: #f4f4f4; /* Fondo claro */\n"
"    color: #333; /* Texto oscuro */\n"
"    border: 2px solid #ccc; /* Borde inicial */\n"
"    border-radius: 10px; /* Bordes redondeados */\n"
"    padding: 8px; /* Espaciado interno */\n"
"    font-size: 14px; /* Tamaño de texto */\n"
"    font-family: \"Arial\", sans-serif; /* Fuente limpia y moderna */\n"
"}\n"
"\n"
"QLineEdit:focus {\n"
"    border: 2px solid #6200ee; /* Cambia el color del borde al enfocarse */\n"
"    background-color: #ffffff; /* Fondo blanco al enfocarse */\n"
"    color: #000; /* Texto más oscuro */\n"
"}")
        self.txtDireccionEdit.setObjectName("txtDireccionEdit")
        self.txtCorreoEdit = QtWidgets.QLineEdit(parent=self.page_EditarPropietario)
        self.txtCorreoEdit.setGeometry(QtCore.QRect(270, 350, 221, 51))
        self.txtCorreoEdit.setStyleSheet("QLineEdit {\n"
"    background-color: #f4f4f4; /* Fondo claro */\n"
"    color: #333; /* Texto oscuro */\n"
"    border: 2px solid #ccc; /* Borde inicial */\n"
"    border-radius: 10px; /* Bordes redondeados */\n"
"    padding: 8px; /* Espaciado interno */\n"
"    font-size: 14px; /* Tamaño de texto */\n"
"    font-family: \"Arial\", sans-serif; /* Fuente limpia y moderna */\n"
"}\n"
"\n"
"QLineEdit:focus {\n"
"    border: 2px solid #6200ee; /* Cambia el color del borde al enfocarse */\n"
"    background-color: #ffffff; /* Fondo blanco al enfocarse */\n"
"    color: #000; /* Texto más oscuro */\n"
"}")
        self.txtCorreoEdit.setObjectName("txtCorreoEdit")
        self.txtTelefonoEdit = QtWidgets.QLineEdit(parent=self.page_EditarPropietario)
        self.txtTelefonoEdit.setGeometry(QtCore.QRect(270, 410, 221, 51))
        self.txtTelefonoEdit.setStyleSheet("QLineEdit {\n"
"    background-color: #f4f4f4; /* Fondo claro */\n"
"    color: #333; /* Texto oscuro */\n"
"    border: 2px solid #ccc; /* Borde inicial */\n"
"    border-radius: 10px; /* Bordes redondeados */\n"
"    padding: 8px; /* Espaciado interno */\n"
"    font-size: 14px; /* Tamaño de texto */\n"
"    font-family: \"Arial\", sans-serif; /* Fuente limpia y moderna */\n"
"}\n"
"\n"
"QLineEdit:focus {\n"
"    border: 2px solid #6200ee; /* Cambia el color del borde al enfocarse */\n"
"    background-color: #ffffff; /* Fondo blanco al enfocarse */\n"
"    color: #000; /* Texto más oscuro */\n"
"}")
        self.txtTelefonoEdit.setObjectName("txtTelefonoEdit")
        self.txtDniEdit = QtWidgets.QLineEdit(parent=self.page_EditarPropietario)
        self.txtDniEdit.setGeometry(QtCore.QRect(270, 110, 221, 51))
        self.txtDniEdit.setStyleSheet("QLineEdit {\n"
"    background-color: #f4f4f4; /* Fondo claro */\n"
"    color: #333; /* Texto oscuro */\n"
"    border: 2px solid #ccc; /* Borde inicial */\n"
"    border-radius: 10px; /* Bordes redondeados */\n"
"    padding: 8px; /* Espaciado interno */\n"
"    font-size: 14px; /* Tamaño de texto */\n"
"    font-family: \"Arial\", sans-serif; /* Fuente limpia y moderna */\n"
"}\n"
"\n"
"QLineEdit:focus {\n"
"    border: 2px solid #6200ee; /* Cambia el color del borde al enfocarse */\n"
"    background-color: #ffffff; /* Fondo blanco al enfocarse */\n"
"    color: #000; /* Texto más oscuro */\n"
"}")
        self.txtDniEdit.setObjectName("txtDniEdit")
        self.btnEditarPropietario = QtWidgets.QPushButton(parent=self.page_EditarPropietario)
        self.btnEditarPropietario.setGeometry(QtCore.QRect(300, 480, 161, 51))
        self.btnEditarPropietario.setObjectName("btnEditarPropietario")
        self.label_7 = QtWidgets.QLabel(parent=self.page_EditarPropietario)
        self.label_7.setGeometry(QtCore.QRect(140, 30, 451, 51))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        self.label_7.setFont(font)
        self.label_7.setTextFormat(QtCore.Qt.TextFormat.AutoText)
        self.label_7.setWordWrap(False)
        self.label_7.setObjectName("label_7")
        self.stackedWidget.addWidget(self.page_EditarPropietario)
        self.page_verPractica = QtWidgets.QWidget()
        self.page_verPractica.setLayoutDirection(QtCore.Qt.LayoutDirection.LeftToRight)
        self.page_verPractica.setObjectName("page_verPractica")
        self.btnBuscarIdpractica = QtWidgets.QPushButton(parent=self.page_verPractica)
        self.btnBuscarIdpractica.setGeometry(QtCore.QRect(500, 190, 151, 24))
        self.btnBuscarIdpractica.setObjectName("btnBuscarIdpractica")
        self.txtIdPracticaFiltro = QtWidgets.QLineEdit(parent=self.page_verPractica)
        self.txtIdPracticaFiltro.setGeometry(QtCore.QRect(240, 180, 191, 41))
        self.txtIdPracticaFiltro.setStyleSheet("QLineEdit {\n"
"    background-color: #f4f4f4; /* Fondo claro */\n"
"    color: #333; /* Texto oscuro */\n"
"    border: 2px solid #ccc; /* Borde inicial */\n"
"    border-radius: 10px; /* Bordes redondeados */\n"
"    padding: 8px; /* Espaciado interno */\n"
"    font-size: 14px; /* Tamaño de texto */\n"
"    font-family: \"Arial\", sans-serif; /* Fuente limpia y moderna */\n"
"}\n"
"\n"
"QLineEdit:focus {\n"
"    border: 2px solid #6200ee; /* Cambia el color del borde al enfocarse */\n"
"    background-color: #ffffff; /* Fondo blanco al enfocarse */\n"
"    color: #000; /* Texto más oscuro */\n"
"}")
        self.txtIdPracticaFiltro.setObjectName("txtIdPracticaFiltro")
        self.grdPractica = QtWidgets.QTableWidget(parent=self.page_verPractica)
        self.grdPractica.setGeometry(QtCore.QRect(280, 290, 221, 281))
        self.grdPractica.setObjectName("grdPractica")
        self.grdPractica.setColumnCount(2)
        self.grdPractica.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.grdPractica.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.grdPractica.setHorizontalHeaderItem(1, item)
        self.stackedWidget.addWidget(self.page_verPractica)
        self.page_AgregarAtencion = QtWidgets.QWidget()
        self.page_AgregarAtencion.setObjectName("page_AgregarAtencion")
        self.txtCodMascota = QtWidgets.QLineEdit(parent=self.page_AgregarAtencion)
        self.txtCodMascota.setGeometry(QtCore.QRect(280, 90, 191, 51))
        self.txtCodMascota.setStyleSheet("QLineEdit {\n"
"    background-color: #f4f4f4; /* Fondo claro */\n"
"    color: #333; /* Texto oscuro */\n"
"    border: 2px solid #ccc; /* Borde inicial */\n"
"    border-radius: 10px; /* Bordes redondeados */\n"
"    padding: 8px; /* Espaciado interno */\n"
"    font-size: 14px; /* Tamaño de texto */\n"
"    font-family: \"Arial\", sans-serif; /* Fuente limpia y moderna */\n"
"}\n"
"\n"
"QLineEdit:focus {\n"
"    border: 2px solid #6200ee; /* Cambia el color del borde al enfocarse */\n"
"    background-color: #ffffff; /* Fondo blanco al enfocarse */\n"
"    color: #000; /* Texto más oscuro */\n"
"}")
        self.txtCodMascota.setObjectName("txtCodMascota")
        self.txtLegajo = QtWidgets.QLineEdit(parent=self.page_AgregarAtencion)
        self.txtLegajo.setGeometry(QtCore.QRect(280, 150, 191, 51))
        self.txtLegajo.setStyleSheet("QLineEdit {\n"
"    background-color: #f4f4f4; /* Fondo claro */\n"
"    color: #333; /* Texto oscuro */\n"
"    border: 2px solid #ccc; /* Borde inicial */\n"
"    border-radius: 10px; /* Bordes redondeados */\n"
"    padding: 8px; /* Espaciado interno */\n"
"    font-size: 14px; /* Tamaño de texto */\n"
"    font-family: \"Arial\", sans-serif; /* Fuente limpia y moderna */\n"
"}\n"
"\n"
"QLineEdit:focus {\n"
"    border: 2px solid #6200ee; /* Cambia el color del borde al enfocarse */\n"
"    background-color: #ffffff; /* Fondo blanco al enfocarse */\n"
"    color: #000; /* Texto más oscuro */\n"
"}")
        self.txtLegajo.setObjectName("txtLegajo")
        self.label_2 = QtWidgets.QLabel(parent=self.page_AgregarAtencion)
        self.label_2.setGeometry(QtCore.QRect(130, 30, 451, 51))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        self.label_2.setFont(font)
        self.label_2.setTextFormat(QtCore.Qt.TextFormat.AutoText)
        self.label_2.setWordWrap(False)
        self.label_2.setObjectName("label_2")
        self.btnInsertarAtencion = QtWidgets.QPushButton(parent=self.page_AgregarAtencion)
        self.btnInsertarAtencion.setGeometry(QtCore.QRect(290, 210, 161, 41))
        self.btnInsertarAtencion.setObjectName("btnInsertarAtencion")
        self.stackedWidget.addWidget(self.page_AgregarAtencion)
        self.page_agregarPractica = QtWidgets.QWidget()
        self.page_agregarPractica.setObjectName("page_agregarPractica")
        self.btnEditarMascota_5 = QtWidgets.QPushButton(parent=self.page_agregarPractica)
        self.btnEditarMascota_5.setGeometry(QtCore.QRect(290, 420, 141, 51))
        self.btnEditarMascota_5.setObjectName("btnEditarMascota_5")
        self.label_12 = QtWidgets.QLabel(parent=self.page_agregarPractica)
        self.label_12.setGeometry(QtCore.QRect(280, 200, 211, 51))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        self.label_12.setFont(font)
        self.label_12.setTextFormat(QtCore.Qt.TextFormat.AutoText)
        self.label_12.setWordWrap(False)
        self.label_12.setObjectName("label_12")
        self.txtCodMascotaEdit_6 = QtWidgets.QLineEdit(parent=self.page_agregarPractica)
        self.txtCodMascotaEdit_6.setGeometry(QtCore.QRect(250, 340, 221, 51))
        self.txtCodMascotaEdit_6.setStyleSheet("QLineEdit {\n"
"    background-color: #f4f4f4; /* Fondo claro */\n"
"    color: #333; /* Texto oscuro */\n"
"    border: 2px solid #ccc; /* Borde inicial */\n"
"    border-radius: 10px; /* Bordes redondeados */\n"
"    padding: 8px; /* Espaciado interno */\n"
"    font-size: 14px; /* Tamaño de texto */\n"
"    font-family: \"Arial\", sans-serif; /* Fuente limpia y moderna */\n"
"}\n"
"\n"
"QLineEdit:focus {\n"
"    border: 2px solid #6200ee; /* Cambia el color del borde al enfocarse */\n"
"    background-color: #ffffff; /* Fondo blanco al enfocarse */\n"
"    color: #000; /* Texto más oscuro */\n"
"}")
        self.txtCodMascotaEdit_6.setObjectName("txtCodMascotaEdit_6")
        self.stackedWidget.addWidget(self.page_agregarPractica)
        self.page_VerAtencion = QtWidgets.QWidget()
        self.page_VerAtencion.setObjectName("page_VerAtencion")
        self.txtBuscarCodMasco = QtWidgets.QLineEdit(parent=self.page_VerAtencion)
        self.txtBuscarCodMasco.setGeometry(QtCore.QRect(180, 110, 191, 41))
        self.txtBuscarCodMasco.setStyleSheet("QLineEdit {\n"
"    background-color: #f4f4f4; /* Fondo claro */\n"
"    color: #333; /* Texto oscuro */\n"
"    border: 2px solid #ccc; /* Borde inicial */\n"
"    border-radius: 10px; /* Bordes redondeados */\n"
"    padding: 8px; /* Espaciado interno */\n"
"    font-size: 14px; /* Tamaño de texto */\n"
"    font-family: \"Arial\", sans-serif; /* Fuente limpia y moderna */\n"
"}\n"
"\n"
"QLineEdit:focus {\n"
"    border: 2px solid #6200ee; /* Cambia el color del borde al enfocarse */\n"
"    background-color: #ffffff; /* Fondo blanco al enfocarse */\n"
"    color: #000; /* Texto más oscuro */\n"
"}")
        self.txtBuscarCodMasco.setObjectName("txtBuscarCodMasco")
        self.btnFiltroCodMasco = QtWidgets.QPushButton(parent=self.page_VerAtencion)
        self.btnFiltroCodMasco.setGeometry(QtCore.QRect(420, 120, 181, 24))
        self.btnFiltroCodMasco.setObjectName("btnFiltroCodMasco")
        self.grdAtencion = QtWidgets.QTableWidget(parent=self.page_VerAtencion)
        self.grdAtencion.setGeometry(QtCore.QRect(200, 240, 401, 281))
        self.grdAtencion.setObjectName("grdAtencion")
        self.grdAtencion.setColumnCount(4)
        self.grdAtencion.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.grdAtencion.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.grdAtencion.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.grdAtencion.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.grdAtencion.setHorizontalHeaderItem(3, item)
        self.stackedWidget.addWidget(self.page_VerAtencion)
        self.page_AgregarMascota = QtWidgets.QWidget()
        self.page_AgregarMascota.setObjectName("page_AgregarMascota")
        self.txtCodMascotaAgregar = QtWidgets.QLineEdit(parent=self.page_AgregarMascota)
        self.txtCodMascotaAgregar.setGeometry(QtCore.QRect(260, 150, 221, 51))
        self.txtCodMascotaAgregar.setStyleSheet("QLineEdit {\n"
"    background-color: #f4f4f4; /* Fondo claro */\n"
"    color: #333; /* Texto oscuro */\n"
"    border: 2px solid #ccc; /* Borde inicial */\n"
"    border-radius: 10px; /* Bordes redondeados */\n"
"    padding: 8px; /* Espaciado interno */\n"
"    font-size: 14px; /* Tamaño de texto */\n"
"    font-family: \"Arial\", sans-serif; /* Fuente limpia y moderna */\n"
"}\n"
"\n"
"QLineEdit:focus {\n"
"    border: 2px solid #6200ee; /* Cambia el color del borde al enfocarse */\n"
"    background-color: #ffffff; /* Fondo blanco al enfocarse */\n"
"    color: #000; /* Texto más oscuro */\n"
"}")
        self.txtCodMascotaAgregar.setObjectName("txtCodMascotaAgregar")
        self.txtDniMascoAgregar = QtWidgets.QLineEdit(parent=self.page_AgregarMascota)
        self.txtDniMascoAgregar.setGeometry(QtCore.QRect(260, 210, 221, 51))
        self.txtDniMascoAgregar.setStyleSheet("QLineEdit {\n"
"    background-color: #f4f4f4; /* Fondo claro */\n"
"    color: #333; /* Texto oscuro */\n"
"    border: 2px solid #ccc; /* Borde inicial */\n"
"    border-radius: 10px; /* Bordes redondeados */\n"
"    padding: 8px; /* Espaciado interno */\n"
"    font-size: 14px; /* Tamaño de texto */\n"
"    font-family: \"Arial\", sans-serif; /* Fuente limpia y moderna */\n"
"}\n"
"\n"
"QLineEdit:focus {\n"
"    border: 2px solid #6200ee; /* Cambia el color del borde al enfocarse */\n"
"    background-color: #ffffff; /* Fondo blanco al enfocarse */\n"
"    color: #000; /* Texto más oscuro */\n"
"}")
        self.txtDniMascoAgregar.setObjectName("txtDniMascoAgregar")
        self.txtRazaAgregar_2 = QtWidgets.QLineEdit(parent=self.page_AgregarMascota)
        self.txtRazaAgregar_2.setGeometry(QtCore.QRect(260, 280, 221, 51))
        self.txtRazaAgregar_2.setStyleSheet("QLineEdit {\n"
"    background-color: #f4f4f4; /* Fondo claro */\n"
"    color: #333; /* Texto oscuro */\n"
"    border: 2px solid #ccc; /* Borde inicial */\n"
"    border-radius: 10px; /* Bordes redondeados */\n"
"    padding: 8px; /* Espaciado interno */\n"
"    font-size: 14px; /* Tamaño de texto */\n"
"    font-family: \"Arial\", sans-serif; /* Fuente limpia y moderna */\n"
"}\n"
"\n"
"QLineEdit:focus {\n"
"    border: 2px solid #6200ee; /* Cambia el color del borde al enfocarse */\n"
"    background-color: #ffffff; /* Fondo blanco al enfocarse */\n"
"    color: #000; /* Texto más oscuro */\n"
"}")
        self.txtRazaAgregar_2.setText("")
        self.txtRazaAgregar_2.setObjectName("txtRazaAgregar_2")
        self.txtGeneroAgregar = QtWidgets.QLineEdit(parent=self.page_AgregarMascota)
        self.txtGeneroAgregar.setGeometry(QtCore.QRect(260, 350, 221, 51))
        self.txtGeneroAgregar.setStyleSheet("QLineEdit {\n"
"    background-color: #f4f4f4; /* Fondo claro */\n"
"    color: #333; /* Texto oscuro */\n"
"    border: 2px solid #ccc; /* Borde inicial */\n"
"    border-radius: 10px; /* Bordes redondeados */\n"
"    padding: 8px; /* Espaciado interno */\n"
"    font-size: 14px; /* Tamaño de texto */\n"
"    font-family: \"Arial\", sans-serif; /* Fuente limpia y moderna */\n"
"}\n"
"\n"
"QLineEdit:focus {\n"
"    border: 2px solid #6200ee; /* Cambia el color del borde al enfocarse */\n"
"    background-color: #ffffff; /* Fondo blanco al enfocarse */\n"
"    color: #000; /* Texto más oscuro */\n"
"}")
        self.txtGeneroAgregar.setText("")
        self.txtGeneroAgregar.setObjectName("txtGeneroAgregar")
        self.txtPesoAgregar = QtWidgets.QLineEdit(parent=self.page_AgregarMascota)
        self.txtPesoAgregar.setGeometry(QtCore.QRect(260, 410, 221, 51))
        self.txtPesoAgregar.setStyleSheet("QLineEdit {\n"
"    background-color: #f4f4f4; /* Fondo claro */\n"
"    color: #333; /* Texto oscuro */\n"
"    border: 2px solid #ccc; /* Borde inicial */\n"
"    border-radius: 10px; /* Bordes redondeados */\n"
"    padding: 8px; /* Espaciado interno */\n"
"    font-size: 14px; /* Tamaño de texto */\n"
"    font-family: \"Arial\", sans-serif; /* Fuente limpia y moderna */\n"
"}\n"
"\n"
"QLineEdit:focus {\n"
"    border: 2px solid #6200ee; /* Cambia el color del borde al enfocarse */\n"
"    background-color: #ffffff; /* Fondo blanco al enfocarse */\n"
"    color: #000; /* Texto más oscuro */\n"
"}")
        self.txtPesoAgregar.setText("")
        self.txtPesoAgregar.setObjectName("txtPesoAgregar")
        self.txtFechaNacimientoAgregar = QtWidgets.QDateEdit(parent=self.page_AgregarMascota)
        self.txtFechaNacimientoAgregar.setGeometry(QtCore.QRect(260, 540, 231, 51))
        self.txtFechaNacimientoAgregar.setObjectName("txtFechaNacimientoAgregar")
        self.btnAgregarMascota = QtWidgets.QPushButton(parent=self.page_AgregarMascota)
        self.btnAgregarMascota.setGeometry(QtCore.QRect(260, 680, 171, 71))
        self.btnAgregarMascota.setObjectName("btnAgregarMascota")
        self.label_8 = QtWidgets.QLabel(parent=self.page_AgregarMascota)
        self.label_8.setGeometry(QtCore.QRect(290, 60, 161, 51))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        self.label_8.setFont(font)
        self.label_8.setTextFormat(QtCore.Qt.TextFormat.AutoText)
        self.label_8.setWordWrap(False)
        self.label_8.setObjectName("label_8")
        self.txtApodoMasco = QtWidgets.QLineEdit(parent=self.page_AgregarMascota)
        self.txtApodoMasco.setGeometry(QtCore.QRect(260, 480, 221, 51))
        self.txtApodoMasco.setStyleSheet("QLineEdit {\n"
"    background-color: #f4f4f4; /* Fondo claro */\n"
"    color: #333; /* Texto oscuro */\n"
"    border: 2px solid #ccc; /* Borde inicial */\n"
"    border-radius: 10px; /* Bordes redondeados */\n"
"    padding: 8px; /* Espaciado interno */\n"
"    font-size: 14px; /* Tamaño de texto */\n"
"    font-family: \"Arial\", sans-serif; /* Fuente limpia y moderna */\n"
"}\n"
"\n"
"QLineEdit:focus {\n"
"    border: 2px solid #6200ee; /* Cambia el color del borde al enfocarse */\n"
"    background-color: #ffffff; /* Fondo blanco al enfocarse */\n"
"    color: #000; /* Texto más oscuro */\n"
"}")
        self.txtApodoMasco.setText("")
        self.txtApodoMasco.setObjectName("txtApodoMasco")
        self.txtObservacionMasco = QtWidgets.QTextEdit(parent=self.page_AgregarMascota)
        self.txtObservacionMasco.setGeometry(QtCore.QRect(250, 600, 251, 71))
        self.txtObservacionMasco.setObjectName("txtObservacionMasco")
        self.stackedWidget.addWidget(self.page_AgregarMascota)
        self.page_EditarEmpleado = QtWidgets.QWidget()
        self.page_EditarEmpleado.setObjectName("page_EditarEmpleado")
        self.label_4 = QtWidgets.QLabel(parent=self.page_EditarEmpleado)
        self.label_4.setGeometry(QtCore.QRect(90, 30, 451, 51))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        self.label_4.setFont(font)
        self.label_4.setTextFormat(QtCore.Qt.TextFormat.AutoText)
        self.label_4.setWordWrap(False)
        self.label_4.setObjectName("label_4")
        self.txtNombreEmp = QtWidgets.QLineEdit(parent=self.page_EditarEmpleado)
        self.txtNombreEmp.setGeometry(QtCore.QRect(300, 150, 191, 51))
        self.txtNombreEmp.setStyleSheet("QLineEdit {\n"
"    background-color: #f4f4f4; /* Fondo claro */\n"
"    color: #333; /* Texto oscuro */\n"
"    border: 2px solid #ccc; /* Borde inicial */\n"
"    border-radius: 10px; /* Bordes redondeados */\n"
"    padding: 8px; /* Espaciado interno */\n"
"    font-size: 14px; /* Tamaño de texto */\n"
"    font-family: \"Arial\", sans-serif; /* Fuente limpia y moderna */\n"
"}\n"
"\n"
"QLineEdit:focus {\n"
"    border: 2px solid #6200ee; /* Cambia el color del borde al enfocarse */\n"
"    background-color: #ffffff; /* Fondo blanco al enfocarse */\n"
"    color: #000; /* Texto más oscuro */\n"
"}")
        self.txtNombreEmp.setObjectName("txtNombreEmp")
        self.ddlTipoPractica = QtWidgets.QComboBox(parent=self.page_EditarEmpleado)
        self.ddlTipoPractica.setGeometry(QtCore.QRect(300, 210, 181, 41))
        self.ddlTipoPractica.setObjectName("ddlTipoPractica")
        self.txtApellidoEmp = QtWidgets.QLineEdit(parent=self.page_EditarEmpleado)
        self.txtApellidoEmp.setGeometry(QtCore.QRect(300, 260, 191, 51))
        self.txtApellidoEmp.setStyleSheet("QLineEdit {\n"
"    background-color: #f4f4f4; /* Fondo claro */\n"
"    color: #333; /* Texto oscuro */\n"
"    border: 2px solid #ccc; /* Borde inicial */\n"
"    border-radius: 10px; /* Bordes redondeados */\n"
"    padding: 8px; /* Espaciado interno */\n"
"    font-size: 14px; /* Tamaño de texto */\n"
"    font-family: \"Arial\", sans-serif; /* Fuente limpia y moderna */\n"
"}\n"
"\n"
"QLineEdit:focus {\n"
"    border: 2px solid #6200ee; /* Cambia el color del borde al enfocarse */\n"
"    background-color: #ffffff; /* Fondo blanco al enfocarse */\n"
"    color: #000; /* Texto más oscuro */\n"
"}")
        self.txtApellidoEmp.setObjectName("txtApellidoEmp")
        self.txtCorreoEmp = QtWidgets.QLineEdit(parent=self.page_EditarEmpleado)
        self.txtCorreoEmp.setGeometry(QtCore.QRect(300, 320, 191, 51))
        self.txtCorreoEmp.setStyleSheet("QLineEdit {\n"
"    background-color: #f4f4f4; /* Fondo claro */\n"
"    color: #333; /* Texto oscuro */\n"
"    border: 2px solid #ccc; /* Borde inicial */\n"
"    border-radius: 10px; /* Bordes redondeados */\n"
"    padding: 8px; /* Espaciado interno */\n"
"    font-size: 14px; /* Tamaño de texto */\n"
"    font-family: \"Arial\", sans-serif; /* Fuente limpia y moderna */\n"
"}\n"
"\n"
"QLineEdit:focus {\n"
"    border: 2px solid #6200ee; /* Cambia el color del borde al enfocarse */\n"
"    background-color: #ffffff; /* Fondo blanco al enfocarse */\n"
"    color: #000; /* Texto más oscuro */\n"
"}")
        self.txtCorreoEmp.setObjectName("txtCorreoEmp")
        self.txtTelefonoEmp = QtWidgets.QLineEdit(parent=self.page_EditarEmpleado)
        self.txtTelefonoEmp.setGeometry(QtCore.QRect(300, 390, 191, 51))
        self.txtTelefonoEmp.setStyleSheet("QLineEdit {\n"
"    background-color: #f4f4f4; /* Fondo claro */\n"
"    color: #333; /* Texto oscuro */\n"
"    border: 2px solid #ccc; /* Borde inicial */\n"
"    border-radius: 10px; /* Bordes redondeados */\n"
"    padding: 8px; /* Espaciado interno */\n"
"    font-size: 14px; /* Tamaño de texto */\n"
"    font-family: \"Arial\", sans-serif; /* Fuente limpia y moderna */\n"
"}\n"
"\n"
"QLineEdit:focus {\n"
"    border: 2px solid #6200ee; /* Cambia el color del borde al enfocarse */\n"
"    background-color: #ffffff; /* Fondo blanco al enfocarse */\n"
"    color: #000; /* Texto más oscuro */\n"
"}")
        self.txtTelefonoEmp.setObjectName("txtTelefonoEmp")
        self.btnEditarEmpleado = QtWidgets.QPushButton(parent=self.page_EditarEmpleado)
        self.btnEditarEmpleado.setGeometry(QtCore.QRect(300, 480, 151, 51))
        self.btnEditarEmpleado.setObjectName("btnEditarEmpleado")
        self.txtLegajoEmpleado = QtWidgets.QLineEdit(parent=self.page_EditarEmpleado)
        self.txtLegajoEmpleado.setGeometry(QtCore.QRect(280, 80, 241, 51))
        self.txtLegajoEmpleado.setStyleSheet("QLineEdit {\n"
"    background-color: #f4f4f4; /* Fondo claro */\n"
"    color: #333; /* Texto oscuro */\n"
"    border: 2px solid #ccc; /* Borde inicial */\n"
"    border-radius: 10px; /* Bordes redondeados */\n"
"    padding: 8px; /* Espaciado interno */\n"
"    font-size: 14px; /* Tamaño de texto */\n"
"    font-family: \"Arial\", sans-serif; /* Fuente limpia y moderna */\n"
"}\n"
"\n"
"QLineEdit:focus {\n"
"    border: 2px solid #6200ee; /* Cambia el color del borde al enfocarse */\n"
"    background-color: #ffffff; /* Fondo blanco al enfocarse */\n"
"    color: #000; /* Texto más oscuro */\n"
"}")
        self.txtLegajoEmpleado.setObjectName("txtLegajoEmpleado")
        self.stackedWidget.addWidget(self.page_EditarEmpleado)
        self.page_AgregarEmp = QtWidgets.QWidget()
        self.page_AgregarEmp.setObjectName("page_AgregarEmp")
        self.txtTelefonoEmpAgregar = QtWidgets.QLineEdit(parent=self.page_AgregarEmp)
        self.txtTelefonoEmpAgregar.setGeometry(QtCore.QRect(440, 480, 211, 51))
        self.txtTelefonoEmpAgregar.setStyleSheet("QLineEdit {\n"
"    background-color: #f4f4f4; /* Fondo claro */\n"
"    color: #333; /* Texto oscuro */\n"
"    border: 2px solid #ccc; /* Borde inicial */\n"
"    border-radius: 10px; /* Bordes redondeados */\n"
"    padding: 8px; /* Espaciado interno */\n"
"    font-size: 14px; /* Tamaño de texto */\n"
"    font-family: \"Arial\", sans-serif; /* Fuente limpia y moderna */\n"
"}\n"
"\n"
"QLineEdit:focus {\n"
"    border: 2px solid #6200ee; /* Cambia el color del borde al enfocarse */\n"
"    background-color: #ffffff; /* Fondo blanco al enfocarse */\n"
"    color: #000; /* Texto más oscuro */\n"
"}")
        self.txtTelefonoEmpAgregar.setObjectName("txtTelefonoEmpAgregar")
        self.txtCorreoEmpAgregar = QtWidgets.QLineEdit(parent=self.page_AgregarEmp)
        self.txtCorreoEmpAgregar.setGeometry(QtCore.QRect(440, 410, 211, 51))
        self.txtCorreoEmpAgregar.setStyleSheet("QLineEdit {\n"
"    background-color: #f4f4f4; /* Fondo claro */\n"
"    color: #333; /* Texto oscuro */\n"
"    border: 2px solid #ccc; /* Borde inicial */\n"
"    border-radius: 10px; /* Bordes redondeados */\n"
"    padding: 8px; /* Espaciado interno */\n"
"    font-size: 14px; /* Tamaño de texto */\n"
"    font-family: \"Arial\", sans-serif; /* Fuente limpia y moderna */\n"
"}\n"
"\n"
"QLineEdit:focus {\n"
"    border: 2px solid #6200ee; /* Cambia el color del borde al enfocarse */\n"
"    background-color: #ffffff; /* Fondo blanco al enfocarse */\n"
"    color: #000; /* Texto más oscuro */\n"
"}")
        self.txtCorreoEmpAgregar.setObjectName("txtCorreoEmpAgregar")
        self.label_26 = QtWidgets.QLabel(parent=self.page_AgregarEmp)
        self.label_26.setGeometry(QtCore.QRect(430, 120, 221, 51))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        self.label_26.setFont(font)
        self.label_26.setTextFormat(QtCore.Qt.TextFormat.AutoText)
        self.label_26.setWordWrap(False)
        self.label_26.setObjectName("label_26")
        self.ddlTipoPracticaAgregarEmp = QtWidgets.QComboBox(parent=self.page_AgregarEmp)
        self.ddlTipoPracticaAgregarEmp.setGeometry(QtCore.QRect(440, 300, 211, 41))
        self.ddlTipoPracticaAgregarEmp.setObjectName("ddlTipoPracticaAgregarEmp")
        self.btnEditarEmpleado_3 = QtWidgets.QPushButton(parent=self.page_AgregarEmp)
        self.btnEditarEmpleado_3.setGeometry(QtCore.QRect(460, 630, 151, 51))
        self.btnEditarEmpleado_3.setObjectName("btnEditarEmpleado_3")
        self.txtApellidoEmpAgregar = QtWidgets.QLineEdit(parent=self.page_AgregarEmp)
        self.txtApellidoEmpAgregar.setGeometry(QtCore.QRect(440, 350, 211, 51))
        self.txtApellidoEmpAgregar.setStyleSheet("QLineEdit {\n"
"    background-color: #f4f4f4; /* Fondo claro */\n"
"    color: #333; /* Texto oscuro */\n"
"    border: 2px solid #ccc; /* Borde inicial */\n"
"    border-radius: 10px; /* Bordes redondeados */\n"
"    padding: 8px; /* Espaciado interno */\n"
"    font-size: 14px; /* Tamaño de texto */\n"
"    font-family: \"Arial\", sans-serif; /* Fuente limpia y moderna */\n"
"}\n"
"\n"
"QLineEdit:focus {\n"
"    border: 2px solid #6200ee; /* Cambia el color del borde al enfocarse */\n"
"    background-color: #ffffff; /* Fondo blanco al enfocarse */\n"
"    color: #000; /* Texto más oscuro */\n"
"}")
        self.txtApellidoEmpAgregar.setObjectName("txtApellidoEmpAgregar")
        self.txtNombreEmpAgregar = QtWidgets.QLineEdit(parent=self.page_AgregarEmp)
        self.txtNombreEmpAgregar.setGeometry(QtCore.QRect(440, 240, 221, 51))
        self.txtNombreEmpAgregar.setStyleSheet("QLineEdit {\n"
"    background-color: #f4f4f4; /* Fondo claro */\n"
"    color: #333; /* Texto oscuro */\n"
"    border: 2px solid #ccc; /* Borde inicial */\n"
"    border-radius: 10px; /* Bordes redondeados */\n"
"    padding: 8px; /* Espaciado interno */\n"
"    font-size: 14px; /* Tamaño de texto */\n"
"    font-family: \"Arial\", sans-serif; /* Fuente limpia y moderna */\n"
"}\n"
"\n"
"QLineEdit:focus {\n"
"    border: 2px solid #6200ee; /* Cambia el color del borde al enfocarse */\n"
"    background-color: #ffffff; /* Fondo blanco al enfocarse */\n"
"    color: #000; /* Texto más oscuro */\n"
"}")
        self.txtNombreEmpAgregar.setObjectName("txtNombreEmpAgregar")
        self.txtLegajoEmpleadoAgregar = QtWidgets.QLineEdit(parent=self.page_AgregarEmp)
        self.txtLegajoEmpleadoAgregar.setGeometry(QtCore.QRect(440, 170, 221, 51))
        self.txtLegajoEmpleadoAgregar.setStyleSheet("QLineEdit {\n"
"    background-color: #f4f4f4; /* Fondo claro */\n"
"    color: #333; /* Texto oscuro */\n"
"    border: 2px solid #ccc; /* Borde inicial */\n"
"    border-radius: 10px; /* Bordes redondeados */\n"
"    padding: 8px; /* Espaciado interno */\n"
"    font-size: 14px; /* Tamaño de texto */\n"
"    font-family: \"Arial\", sans-serif; /* Fuente limpia y moderna */\n"
"}\n"
"\n"
"QLineEdit:focus {\n"
"    border: 2px solid #6200ee; /* Cambia el color del borde al enfocarse */\n"
"    background-color: #ffffff; /* Fondo blanco al enfocarse */\n"
"    color: #000; /* Texto más oscuro */\n"
"}")
        self.txtLegajoEmpleadoAgregar.setObjectName("txtLegajoEmpleadoAgregar")
        self.txtDniEmpAgregar = QtWidgets.QLineEdit(parent=self.page_AgregarEmp)
        self.txtDniEmpAgregar.setGeometry(QtCore.QRect(440, 540, 231, 51))
        self.txtDniEmpAgregar.setStyleSheet("QLineEdit {\n"
"    background-color: #f4f4f4; /* Fondo claro */\n"
"    color: #333; /* Texto oscuro */\n"
"    border: 2px solid #ccc; /* Borde inicial */\n"
"    border-radius: 10px; /* Bordes redondeados */\n"
"    padding: 8px; /* Espaciado interno */\n"
"    font-size: 14px; /* Tamaño de texto */\n"
"    font-family: \"Arial\", sans-serif; /* Fuente limpia y moderna */\n"
"}\n"
"\n"
"QLineEdit:focus {\n"
"    border: 2px solid #6200ee; /* Cambia el color del borde al enfocarse */\n"
"    background-color: #ffffff; /* Fondo blanco al enfocarse */\n"
"    color: #000; /* Texto más oscuro */\n"
"}")
        self.txtDniEmpAgregar.setObjectName("txtDniEmpAgregar")
        self.stackedWidget.addWidget(self.page_AgregarEmp)
        self.page_EliminarEmpleado = QtWidgets.QWidget()
        self.page_EliminarEmpleado.setLayoutDirection(QtCore.Qt.LayoutDirection.LeftToRight)
        self.page_EliminarEmpleado.setObjectName("page_EliminarEmpleado")
        self.btnEliminarEmp = QtWidgets.QPushButton(parent=self.page_EliminarEmpleado)
        self.btnEliminarEmp.setGeometry(QtCore.QRect(250, 270, 141, 41))
        self.btnEliminarEmp.setObjectName("btnEliminarEmp")
        self.txtLegajoEliminar = QtWidgets.QLineEdit(parent=self.page_EliminarEmpleado)
        self.txtLegajoEliminar.setGeometry(QtCore.QRect(180, 200, 291, 51))
        self.txtLegajoEliminar.setStyleSheet("QLineEdit {\n"
"    background-color: #f4f4f4; /* Fondo claro */\n"
"    color: #333; /* Texto oscuro */\n"
"    border: 2px solid #ccc; /* Borde inicial */\n"
"    border-radius: 10px; /* Bordes redondeados */\n"
"    padding: 8px; /* Espaciado interno */\n"
"    font-size: 14px; /* Tamaño de texto */\n"
"    font-family: \"Arial\", sans-serif; /* Fuente limpia y moderna */\n"
"}\n"
"\n"
"QLineEdit:focus {\n"
"    border: 2px solid #6200ee; /* Cambia el color del borde al enfocarse */\n"
"    background-color: #ffffff; /* Fondo blanco al enfocarse */\n"
"    color: #000; /* Texto más oscuro */\n"
"}")
        self.txtLegajoEliminar.setObjectName("txtLegajoEliminar")
        self.label_9 = QtWidgets.QLabel(parent=self.page_EliminarEmpleado)
        self.label_9.setGeometry(QtCore.QRect(250, 120, 151, 51))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        self.label_9.setFont(font)
        self.label_9.setTextFormat(QtCore.Qt.TextFormat.AutoText)
        self.label_9.setWordWrap(False)
        self.label_9.setObjectName("label_9")
        self.stackedWidget.addWidget(self.page_EliminarEmpleado)
        self.verticalLayout_2.addWidget(self.stackedWidget)
        self.horizontalLayout.addWidget(self.frame_2)
        self.verticalLayout.addWidget(self.frame_inferior)
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(parent=MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.stackedWidget.setCurrentIndex(16)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.pushButton_5.setText(_translate("MainWindow", "MENU"))
        self.btnFormEditarProp.setText(_translate("MainWindow", "Editar Propietario"))
        self.btnFormDeletProp.setText(_translate("MainWindow", "Eliminar Propietario"))
        self.btnFormVerMascota.setText(_translate("MainWindow", "Ver Mascotas"))
        self.btnFormEditMascota.setText(_translate("MainWindow", "Editar Mascota"))
        self.btnFormDeletMasco.setText(_translate("MainWindow", "Eliminar Mascota"))
        self.btnFormVerEmp.setText(_translate("MainWindow", "Ver Empleado"))
        self.btnFormEditEmp.setText(_translate("MainWindow", "Editar Empleado"))
        self.btnFormDeletEmp.setText(_translate("MainWindow", "Eliminar Empleado"))
        self.btnFormAtencion.setText(_translate("MainWindow", "Ver Atencion medica"))
        self.btnVerPropietario.setText(_translate("MainWindow", "Ver Propietario"))
        self.btnFormInicio.setText(_translate("MainWindow", "Inicio"))
        self.btnFormAgregarAtencion.setText(_translate("MainWindow", "Agregar Atenciones"))
        self.btnFormEditAtencion.setText(_translate("MainWindow", "Editar Atencion"))
        self.btnFormVerPractica.setText(_translate("MainWindow", "Ver Practicas existentes"))
        self.btnFormAgregarPractica.setText(_translate("MainWindow", "Agregar Practica Medica"))
        self.btnFormAgregarEmp.setText(_translate("MainWindow", "Agregar Empleado"))
        self.btnFormAgregarProp.setText(_translate("MainWindow", "Agregar Propietario"))
        self.btnFormAgregarMascota.setText(_translate("MainWindow", "Agregar Mascota"))
        self.btnEditarMascota_6.setText(_translate("MainWindow", "Aplicar Edicion"))
        self.txtDniMascotaEdit_2.setPlaceholderText(_translate("MainWindow", "Legajo Empleado"))
        self.txtObservacion_2.setPlaceholderText(_translate("MainWindow", "Observaciones"))
        self.txtCodMascotaEdit_7.setPlaceholderText(_translate("MainWindow", "ID Codigo Atencion"))
        self.label_13.setText(_translate("MainWindow", "Editar Atencion"))
        item = self.tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Legajo"))
        item = self.tableWidget.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "ID Practica"))
        item = self.tableWidget.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "DNI "))
        item = self.tableWidget.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "Nombre"))
        item = self.tableWidget.horizontalHeaderItem(4)
        item.setText(_translate("MainWindow", "Apellido"))
        item = self.tableWidget.horizontalHeaderItem(5)
        item.setText(_translate("MainWindow", "Telefono"))
        self.pushButton_17.setText(_translate("MainWindow", "Buscar por Nombre"))
        self.txtNombreFiltroEmp.setPlaceholderText(_translate("MainWindow", "Nombre Empleado"))
        self.label_10.setText(_translate("MainWindow", "Eliminar Mascota"))
        self.btnEliminarMascota.setText(_translate("MainWindow", "Eliminar"))
        self.txtCodMascotaEliminar.setText(_translate("MainWindow", "Codigo Mascota"))
        self.txtCodMascotaEliminar.setPlaceholderText(_translate("MainWindow", "Ingrese Legajo Empleado"))
        self.txtCodMascotaEdit.setPlaceholderText(_translate("MainWindow", "Ingrese Codigo de mascota"))
        self.txtDniMascotaEdit.setPlaceholderText(_translate("MainWindow", "DNI de propietario"))
        self.txtPeso.setPlaceholderText(_translate("MainWindow", "Peso Nuevo"))
        self.txtObservacion.setPlaceholderText(_translate("MainWindow", "Observaciones"))
        self.label_5.setText(_translate("MainWindow", "Cambiar fecha nacimiento"))
        self.label_6.setText(_translate("MainWindow", "Editar Informacion de Mascota"))
        self.btnEditarMascota.setText(_translate("MainWindow", "Aplicar Edicion"))
        self.txtNombreMasco.setPlaceholderText(_translate("MainWindow", "Nombre Nuevo"))
        self.txtNombreFiltroEmp_3.setPlaceholderText(_translate("MainWindow", "Codigo Mascota"))
        self.pushButton_19.setText(_translate("MainWindow", "Buscar por Codigo Mascota"))
        item = self.grdMascotas.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Cod Mascota"))
        item = self.grdMascotas.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "DNI Propietario"))
        item = self.grdMascotas.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Nombre"))
        item = self.grdMascotas.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "Raza"))
        item = self.grdMascotas.horizontalHeaderItem(4)
        item.setText(_translate("MainWindow", "Genero"))
        item = self.grdMascotas.horizontalHeaderItem(5)
        item.setText(_translate("MainWindow", "Peso"))
        item = self.grdMascotas.horizontalHeaderItem(6)
        item.setText(_translate("MainWindow", "Fecha Nacimiento"))
        self.txtNombreFiltroEmp_6.setPlaceholderText(_translate("MainWindow", "Nombre Mascota"))
        self.pushButton_22.setText(_translate("MainWindow", "Buscar por Nombre Mascota"))
        self.label_11.setText(_translate("MainWindow", "Eliminar Propietario"))
        self.btnEmpEliminar.setText(_translate("MainWindow", "Eliminar"))
        self.txtDniEliminar.setText(_translate("MainWindow", "Dni  Propietario a eliminar"))
        self.txtDniEliminar.setPlaceholderText(_translate("MainWindow", "Ingrese Legajo Empleado"))
        self.label_3.setText(_translate("MainWindow", "                            Registre un nuevo Propietario"))
        self.txtDni.setPlaceholderText(_translate("MainWindow", "Ingrese DNI"))
        self.txtNombre.setPlaceholderText(_translate("MainWindow", "Ingrese Nombre"))
        self.txtApellido.setPlaceholderText(_translate("MainWindow", "Ingrese Apellido"))
        self.txtCorreo.setPlaceholderText(_translate("MainWindow", "Ingrese Correo"))
        self.txtTelefono.setPlaceholderText(_translate("MainWindow", "Ingrese Telefono"))
        self.btnInsertarPropietario.setText(_translate("MainWindow", "Registrar"))
        self.txtCorreo_2.setPlaceholderText(_translate("MainWindow", "Direccion"))
        self.txtBuscarDni.setPlaceholderText(_translate("MainWindow", "DNI Propietario"))
        self.btnbuscaDni.setText(_translate("MainWindow", "Buscar por DNI"))
        item = self.grdPropietario.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "DNI"))
        item = self.grdPropietario.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Nombre"))
        item = self.grdPropietario.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Apellido"))
        item = self.grdPropietario.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "Direccion"))
        item = self.grdPropietario.horizontalHeaderItem(4)
        item.setText(_translate("MainWindow", "Correo"))
        item = self.grdPropietario.horizontalHeaderItem(5)
        item.setText(_translate("MainWindow", "Telefono"))
        self.txtNombreEdit.setPlaceholderText(_translate("MainWindow", "Nombre Nuevo"))
        self.txtApellidoEdit.setPlaceholderText(_translate("MainWindow", "Apellido Nuevo"))
        self.txtDireccionEdit.setPlaceholderText(_translate("MainWindow", "Dirreccion nuevo"))
        self.txtCorreoEdit.setPlaceholderText(_translate("MainWindow", "Correo Nuevo"))
        self.txtTelefonoEdit.setPlaceholderText(_translate("MainWindow", "Telefono Nuevo"))
        self.txtDniEdit.setPlaceholderText(_translate("MainWindow", "DNI a editar"))
        self.btnEditarPropietario.setText(_translate("MainWindow", "Aplicar Edicion"))
        self.label_7.setText(_translate("MainWindow", "                         Editar informacion acerca de un propietario"))
        self.btnBuscarIdpractica.setText(_translate("MainWindow", "Buscar por ID Practica"))
        self.txtIdPracticaFiltro.setPlaceholderText(_translate("MainWindow", "ID Practica"))
        item = self.grdPractica.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "ID"))
        item = self.grdPractica.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Descripcion"))
        self.txtCodMascota.setPlaceholderText(_translate("MainWindow", "Codigo Mascota"))
        self.txtLegajo.setPlaceholderText(_translate("MainWindow", "Legajo Empleado"))
        self.label_2.setText(_translate("MainWindow", "                            Registre una nueva Atencion Medica"))
        self.btnInsertarAtencion.setText(_translate("MainWindow", "Registrar"))
        self.btnEditarMascota_5.setText(_translate("MainWindow", "Agregar Practica"))
        self.label_12.setText(_translate("MainWindow", "Agregar Practica"))
        self.txtCodMascotaEdit_6.setText(_translate("MainWindow", "Descripcion"))
        self.txtCodMascotaEdit_6.setPlaceholderText(_translate("MainWindow", "Ingrese Legajo Empleado"))
        self.txtBuscarCodMasco.setPlaceholderText(_translate("MainWindow", "Codigo Mascota"))
        self.btnFiltroCodMasco.setText(_translate("MainWindow", "Buscar por Codigo Mascota"))
        item = self.grdAtencion.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Id Atencion"))
        item = self.grdAtencion.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Legajo"))
        item = self.grdAtencion.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Cod Mascota"))
        item = self.grdAtencion.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "Observacion"))
        self.txtCodMascotaAgregar.setPlaceholderText(_translate("MainWindow", "Ingrese Codigo de mascota"))
        self.txtDniMascoAgregar.setPlaceholderText(_translate("MainWindow", "Ingrese Dni propietario"))
        self.txtRazaAgregar_2.setPlaceholderText(_translate("MainWindow", "Especie"))
        self.txtGeneroAgregar.setPlaceholderText(_translate("MainWindow", "Sexo"))
        self.txtPesoAgregar.setPlaceholderText(_translate("MainWindow", "Peso"))
        self.btnAgregarMascota.setText(_translate("MainWindow", "Agregar Nueva Mascota"))
        self.label_8.setText(_translate("MainWindow", "Registrar Mascota"))
        self.txtApodoMasco.setPlaceholderText(_translate("MainWindow", "Apodo"))
        self.label_4.setText(_translate("MainWindow", "                                                Editar informacion empleado"))
        self.txtNombreEmp.setPlaceholderText(_translate("MainWindow", "Nombre"))
        self.txtApellidoEmp.setPlaceholderText(_translate("MainWindow", "Apellido"))
        self.txtCorreoEmp.setPlaceholderText(_translate("MainWindow", "Correo"))
        self.txtTelefonoEmp.setPlaceholderText(_translate("MainWindow", "Numero Telefono"))
        self.btnEditarEmpleado.setText(_translate("MainWindow", "Aplicar Cambios"))
        self.txtLegajoEmpleado.setPlaceholderText(_translate("MainWindow", "Legajo a quien aplicar edicion"))
        self.txtTelefonoEmpAgregar.setPlaceholderText(_translate("MainWindow", "Numero Telefono"))
        self.txtCorreoEmpAgregar.setPlaceholderText(_translate("MainWindow", "Correo"))
        self.label_26.setText(_translate("MainWindow", "Registrar Nuevo Empleado"))
        self.btnEditarEmpleado_3.setText(_translate("MainWindow", "Aplicar Cambios"))
        self.txtApellidoEmpAgregar.setPlaceholderText(_translate("MainWindow", "Apellido"))
        self.txtNombreEmpAgregar.setPlaceholderText(_translate("MainWindow", "Nombre"))
        self.txtLegajoEmpleadoAgregar.setPlaceholderText(_translate("MainWindow", "Ingrese legajo"))
        self.txtDniEmpAgregar.setPlaceholderText(_translate("MainWindow", "DNI"))
        self.btnEliminarEmp.setText(_translate("MainWindow", "Eliminar"))
        self.txtLegajoEliminar.setPlaceholderText(_translate("MainWindow", "Ingrese Legajo Empleado a eliminar"))
        self.label_9.setText(_translate("MainWindow", "Eliminar Empleado"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec())
